import serial
import time

client = serial.Serial("/dev/ttyUSB0",115200)
time.sleep(1)
print(client.read_all())
print("start")
client.write(b"\x41")
print(client.read_all())
print("read")

#time.sleep(.1)
#client.write(b"B")
#print(client.read())
#time.sleep(0.1)
#client.write(b"C")
#print(client.read())
#time.sleep(0.1)
##client.write(b"D")
##client.read()
##time.sleep(0.1)
##client.write(b"E")
##client.read()
##time.sleep(0.1)
##client.write(b"F")
##client.read()
##time.sleep(0.1)
#print("end")
#time.sleep(1)
